### ISSUE TITLE
failed : deis push deis master

### ISSUE THREAD

**Issue by CloudSide** [jumbojett/deis-ui#8] opened 2016-02-02 05:58 UTC
failed : deis push deis master

```
The command '/bin/sh -c ./node_modules/bower/bin/bower install --allow-root' returned a non-zero code: 1
```

**Comment by bacongobbler** [comment] 2016-02-02 06:33
sounds related to #7

**Comment by bacongobbler** [comment] 2016-02-02 06:59
Yes, this issue is a duplicate of #7.

```
bower                                        ECONFLICT Unable to find suitable version for angular
The command '/bin/sh -c ./node_modules/bower/bin/bower install --allow-root' returned a non-zero code: 1
```

**Closed as completed by bacongobbler** 2016-02-02 06:59 UTC
