### ISSUE TITLE
Can't start the angular app

### ISSUE THREAD

**Issue by alfirin** [jumbojett/deis-ui#13] opened 2016-09-19 06:59 UTC
I got these 4 errors when launching the app:

```
scripts.a358a922.js:1 Uncaught ReferenceError: require is not defined

vendor.1b060f0a.js:2 Uncaught Error: [$injector:unpr] Unknown provider: TokenInterceptorProvider <- TokenInterceptor <- $http <- $compile
```

**Comment by bacongobbler** [comment] 2016-09-19 07:14
closing as a duplicate of #12

**Closed as completed by bacongobbler** 2016-09-19 07:14 UTC
